## Basic Configuration
baseurl = "https://SevillaRusers.netlify.com/"
languageCode = "es"

theme = "hyde-hyde"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Grupo de Usuarios de R de Sevilla"
    title = "SevillaR"
    description = "Grupo de usuarios del lenguaje de programación y programa estadístico R en Sevilla"
    authorimage = "/img/logoSevillaR2.jpg"
    dateformat = "2 Jan 2006"
    highlightjs = true
    # highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id"

## Social Accounts
[params.social]
    github = "SevillaR"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    twitter = "_SevillaR"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    email = "SevillaRUG@gmail.com"
    # forum = "https://groups.google.com/forum/#!forum/sevillarusers"
    # meetup = "https://www.meetup.com/es-ES/Sevilla-R-users/"


## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
